### ISSUE TITLE
[Bug] OptiForge transformation behaviors does not work for OpenJ9 JRE14

### ISSUE THREAD

**Issue by reo-ar** [ZekerZhayard/OptiForge#25]
## Description

OpenJ9 JRE14 works on latest Forge versions fine except for when OptiForge is installed. Where it will throw transformation behavior errors.

## How to reproduce

Run Minecraft Forge with OptiForge and Optifine previews in 1.15.2.

##  Logs
https://paste.ee/p/12xHK

Note: I do understand that OpenJ9 JRE 14 isn't supported officially by Forge, but it does run perfectly fine on the transformation behaviors except for when Optiforge is installed.

**Comment by ZekerZhayard** [comment]
Forge itself does NOT support OpenJ9 JVM.
AdoptOpenJDK 14 with OpenJ9 JVM just happened to modify the value of the `java.vendor` property from `Eclipse OpenJ9` to `AdoptOpenJDK` so that modlauncher couldn't detect it.

See https://github.com/cpw/modlauncher/commit/1f9473a28ad910ef42539f7f789f63afa4cdbf8d
