### ISSUE TITLE
1.12.2 support

### ISSUE THREAD

**Issue by RossComputerGuy** [ZekerZhayard/OptiForge#44]
A lot of mods don't support the newer versions of Minecraft so I think it'll be nice to support 1.12.2

**Comment by RossComputerGuy** [comment]
Why is this invalid?

**Comment by ZekerZhayard** [comment]
If you know what happened after Forge 1.13+, and how OptiFine applies into Minecraft and be compatible with Forge, it is easy to understand why OptiForge exist.

9 years ago, if someone wants to install mods for Minecraft, they must extract the mod, and patch into vanilla Minecraft jar manually. If there are two mods modified the same class file, they will conflict for each.
6 years ago, Mojang published a tool called LegacyLauncher. The purpose of this thing is to adapt the old version of Minecraft to the file structure of the new version of Minecraft, but this thing also provides convenience for other mods to modify the vanilla Minecraft, OptiFine and Forge are this kind of mods. Players no longer extract mods manually, these mods modified Minecraft automatically by LegacyLauncher. However, LegacyLauncher couldn't solve the problem between two mods which replace the same class file, so OptiFine is not compatible with Forge at first although they all used LegacyLauncher. (By the way, there is a project also called OptiForge to solve conflict between OptiFine and Forge at that time, of course the author was not me.) Afterwards, OptiFine hardcoded the forge codes into OptiFine's class files whitch also modified by Forge. In this way, they were compatible finally.
However, when Forge updated theirs code but OptiFine didn't adapt, conflicts arised. This is why OptiFine will crash with Forge 1.14.4-28.2.2 or above. So, one of the sense of OptiForge now is to re-patch new Forge's codes into OptiFine. Because Forge 1.12.2 is no loger updated, and OptiFine has been compatible the latest Forge version in 1.12.2, so I have no reason to backport OptiForge to 1.12.2.

Another sense of OptiForge is that after MInecraft 1.13, Forge team decided not to use LegacyLauncher any more. They developed another launching system called modlauncher, but OptiFine was still using LegacyLauncher, so that OptiFine can't be installed with Forge together. Until Minecraft 1.14.4 release, cpw accorded to the requirements of sp614x(OptiFine author) to improve modlauncher, so that OptiFine can be together again.
However, there are a few bugs about this thing, one of is https://github.com/cpw/modlauncher/issues/37, and OptiForge solved this issue. Becasue Forge 1.12.2 was still using LegacyLauncher, so this problem is not a problem in 1.12.2.

After all, no more reasons for me to make OptiForge 1.12.2.
