### ISSUE TITLE
1.17 forge

### ISSUE THREAD

**Issue by Litttlefish** [ZekerZhayard/OptiForge#86]
1.17.1 forge was out now.

Would you update it?

**Comment by vPubneutral** [comment]
I'm sure he's working on it. Forge for 1.17.1 had to more or less be completely rewritten to get Java 16 to work, and I would imagine most mods are going to have to do some serious under the hood changes as well. A couple of very minor mods have made the switch but OptiForge is easily a lot more complicated then anything that's come out so far for 1.17.1. 

The developer is also responsible for [ForgeWrapper](https://github.com/ZekerZhayard/ForgeWrapper), which has to be updated to work with 1.17 as well. He isn't just the OptiForge dev, he has other projects. It'll get done when it gets done.

**Comment by Eric-01** [comment]
I suppose that the reason may be different.

Since OptiFine hasn't been made compatible with Forge on its own, OptiForge may have to help it and do some hacks to make it work. Such hacks are in the Minecraft modding community called coremods. Forge (usually) supports 2 types of coremods:
* JavaScript coremods (the "proper" way).
As the JavaScript coremods system has been designed by the Forge team, they adapted it to work with the new modular Forge for version 1.17 even before it has been released, so modders can already use it in their mods since day 0.
* Mixin coremods.
Mixin, on the other hand, is Sponge's project, so the Forge team can't easily make modifications to it. As a result, it isn't and won't be compatible with the new modular Forge for 1.17 unless someone from the Sponge team fixes it. Since it doesn't work with Forge yet, the Forge team has decided not to include it with the new modular Forge for 1.17 for the time being.

I guess that either ZekerZhayard has no experience with JavaScript coremodes, or they are not powerful enough to make OptiFine work with the new modular Forge for 1.17.

**Comment by Klouver-github** [comment]
Yippy do yippy Dee you're wish come Magically free. Optiforge 1.17.1 beta out now

**Comment by ZekerZhayard** [comment]
Done
